# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UrlItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Item')),
                ('url', models.URLField()),
            ],
            bases=('api.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node'),
        ),
    ]
